# nginx proxy address - http://172.17.0.1:59069

name: dockge
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: louislam/dockge:latest
    container_name: dockge-app
    hostname: ${BASE_HOST_NAME:-localhost}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      DOCKGE_STACKS_DIR: /opt/stacks
    ports:
      - "172.17.0.1:59069:5001"
    volumes:
      - "./volumes/data/dockge:/app/data"
      - "./volumes/config/dockge:/opt/stacks"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dockge

networks:
  dockge:
    name: dockge
    external: false
